### ISSUE TITLE
Start menu enhancement.

### ISSUE THREAD

**Issue by geekyBoogiepop** [nx-desktop/nx-simplemenu-applet#18] opened 2018-09-04 05:48 UTC
When I open the menu and then it should close pressing the _Super_ key, also if I want to look for some program by typing after open the menu doesn't work.
In addition to the first issue with the menu, when I'm using a program (e.g. VSCode) and I open the menu by pressing super key, it gets the focus, but when I close it by pressing _Esc_ key, the focus doesn't revert to previous program.

**Comment by UriHerrera** [comment] 2018-10-08 02:55
Closing as a dupe of https://github.com/nomad-desktop/nomad-simplemenu-applet/issues/8

**Closed as completed by UriHerrera** 2018-10-08 02:55 UTC
Labels: bug, duplicate, discussion-design
